PAGE_SIZE = 12

PROJECT_NAME_MAX_LEN = 200
USER_NAME_MAX_LEN = 124
SKILL_NAME_MAX_LEN = 124
PHONE_MAX_LEN = 12
ABOUT_MAX_LEN = 256

STATUS_OPEN = 'open'
STATUS_CLOSED = 'closed'

PROJECT_STATUS_CHOICES = (
    (STATUS_OPEN, 'Открыт'),
    (STATUS_CLOSED, 'Закрыт'),
)

PROJECT_STATUS_MAX_LEN = max(len(status) for status, _ in PROJECT_STATUS_CHOICES)
